public class BPConstants 
{
	public static String Profile_SystemAdministrator = 'System Administrator';
	public static String Profile_BPlusCommunity = 'BPlus Community';
	public static String Profile_BPlusManager = 'BPlus Manager';

	public static final String FollowUp_Type_Resume = 'Resume';
	public static final String FollowUp_Type_Interview = 'Interview';
	public static final String FollowUp_Type_CallEmployer = 'Call Employer';
	public static final String FollowUp_Type_CallJobseeker = 'Call Jobseeker';
	public static final String FollowUp_Type_CallJobseekerThenEmployer = 'Call Jobseeker then Employer';

	public static final String EmployerContact_Result_Interview = 'Interview';
	public static final String EmployerContact_Result_ResumeDropOff = 'Resume drop off';
	public static final String EmployerContact_Result_ResumeSent = 'Resume sent';
	public static final String EmployerContact_Result_LeftMessage = 'Left message';
	public static final String EmployerContact_Result_DoNotDisturb = 'Do not disturb';
	public static final String EmployerContact_NoAnswer = 'No Answer';

	public static final String SMSMNotification_Type_CommencedMarketing = 'Commenced Marketing';
	public static final String SMSMNotification_Type_Interview = 'Interview';
	public static final String SMSMNotification_Type_EmployerMeeting = 'Employer Meeting';
	public static final String SMSMNotification_Type_EmployerDetails = 'Employer Details';
}