public class BPConstants 
{
	public static final String FollowUp_Type_Resume = 'Resume';
	public static final String FollowUp_Type_Interview = 'Interview';
	public static final String FollowUp_Type_RepeatCall = 'Repeat call';

	public static final String EmployerContact_Result_Interview = 'Interview';
	public static final String EmployerContact_Result_ResumeDropOff = 'Resume dropoff';
	public static final String EmployerContact_Result_ResumeSent = 'Resume sent';
	public static final String EmployerContact_Result_LeftMessage = 'Left message';
}